#version 460 core
#include "common.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

DEFINE_UNIFORM_BLOCK(0, 0)
{
    PerFrameUniforms perFrameUniforms[2];
};

DEFINE_STORAGE_BLOCK(1, 0)
{
    SceneNode sceneNodes[];
};

DEFINE_STORAGE_BLOCK(1, 1)
{
    SceneMesh sceneMeshes[];
};

DEFINE_STORAGE_BLOCK(1, 2)
{
    IndirectDraw drawCmds[];
};

DEFINE_STORAGE_BLOCK(1, 3)
{
    uint drawCmdCount;
};

DEFINE_CONSTANT_BLOCK
{
    uint nodeCount;
};

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if(idx >= nodeCount)
    {
        return;
    }

    SceneNode node = sceneNodes[idx];
    SceneMesh mesh = sceneMeshes[node.mMeshId];

    uint drawIdx = atomicAdd(drawCmdCount, 1);
    drawCmds[drawIdx].mIndexCount = mesh.mIndexCount;
    drawCmds[drawIdx].mInstanceCount = 1;
    drawCmds[drawIdx].mFirstIndex = mesh.mIndexStart;
    drawCmds[drawIdx].mVertexOffset = mesh.mVertexOffset;
    drawCmds[drawIdx].mFirstInstance = 0;
}
