#version 460 core
#include "common.glsl"

layout(local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

DEFINE_CONSTANT_BLOCK
{
    uint nodeCount;
};

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if(idx >= nodeCount)
    {
        return;
    }

    SceneNode node = sceneNodes[idx];
    SceneMesh mesh = sceneMeshes[node.mMeshId];

    uint drawIdx = atomicAdd(drawCmdCount, 1);
    drawCmds[drawIdx].mIndexCount = mesh.mIndexCount;
    drawCmds[drawIdx].mInstanceCount = 1;
    drawCmds[drawIdx].mFirstIndex = mesh.mIndexStart;
    drawCmds[drawIdx].mVertexOffset = mesh.mVertexOffset;
    drawCmds[drawIdx].mFirstInstance = 0;

    perDraw[drawIdx].mNodeId = idx;
}
