#version 460 core
#include "common.glsl"

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

DEFINE_UNIFORM_BLOCK(0, 0)
{
    PerFrameUniforms perFrameUniforms[2];
};

DEFINE_STORAGE_BLOCK(1, 0)
{
    SceneNode sceneNodes[];
};

DEFINE_STORAGE_BLOCK(1, 1)
{
    SceneMesh sceneMeshes[];
};

DEFINE_STORAGE_BLOCK(1, 2)
{
    IndirectDraw drawCmds[];
};

DEFINE_STORAGE_BLOCK(1, 3)
{
    uint drawCmdCount;
};

DEFINE_CONSTANT_BLOCK
{
    uint nodeCount;
};

uint GetThreadGlobalId()
{
    uvec3 globalSize = gl_NumWorkGroups * gl_WorkGroupSize;
    return
        gl_GlobalInvocationID.x +
        gl_GlobalInvocationID.y * globalSize.x +
        gl_GlobalInvocationID.z * globalSize.x * globalSize.y;
}

void main()
{
    uint idx = GetThreadGlobalId();
    if(idx >= nodeCount)
    {
        return;
    }

    SceneNode node = sceneNodes[idx];
    SceneMesh mesh = sceneMeshes[node.mMeshId];

    drawCmdCount = 0;
    barrier();  // TODO(caio): Is this needed?
    
    uint drawIdx = atomicAdd(drawCmdCount, 1);
    drawCmds[drawIdx].mIndexCount = mesh.mIndexCount;
    drawCmds[drawIdx].mInstanceCount = 1;
    drawCmds[drawIdx].mFirstIndex = mesh.mIndexStart;
    drawCmds[drawIdx].mVertexOffset = mesh.mVertexOffset;
    drawCmds[drawIdx].mFirstInstance = 0;
}
